### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by eric-hansen** [nlamirault/phpunit.el#15]
Not really an issue but want to know something.  I was thinking of writing a PHPUnit minor mode, but then ran across this, and was wondering if you didn't mind me forking the project and creating a PR once the rewrite of making this a minor mode is done?

**Comment by nlamirault** [comment]
Sure !

**Comment by eric-hansen** [comment]
Since this got merged in I'm going to close out my own issue here to reduce the noise/clutter
