### ISSUE TITLE
Specifying the location of phpunit.xml

### ISSUE THREAD

**Issue by ahmadnazir** [nlamirault/phpunit.el#3]
Hi,

The phpunit.xml file name is hard-coded. Also, the default place to look for it is project root which is not true in all cases. I have a Symfony2 application and I usually run my tests as:

phpunit -c /app

The following function needs to be modified:

    (defun phpunit-get-program (args)
      "Return the command to launch unit test.
    `ARGS' corresponds to phpunit command line arguments."
      (s-concat phpunit-program " -c "
	        (phpunit-get-root-directory)
	        "phpunit.xml"
	        args))

This should be something like:

    (defun phpunit-get-program (args)
      "Return the command to launch unit test.
    `ARGS' corresponds to phpunit command line arguments."
      (s-concat phpunit-program " -c "
	        phpunit-configuration-file-path
	        args))

where the phpunit-configuration-file-path should be configurable.

Your thoughts?

**Comment by nlamirault** [comment]
why not.
I'm a newbie in PHP development. I creates this Emacs project for my first PHP project.
Please make a pull request for this changes.
