### ISSUE TITLE
phpunit-current-test is not working

### ISSUE THREAD

**Issue by ZzAntares** [nlamirault/phpunit.el#32]
Hi, as stated in #31 the function `phpunit-current-test` is not working for me but `phpunit-current-class` y `phpunit-current-project` works fine.

The output of `phpunit-current-test` is just:

```
No tests executed!
```

If I run the command `phpunit --filter BillingInfoControllerTest::testShow` which I believe is what `phpunit.el` is doing, the output is the same `No tests executed!`.

However if I change the command to `phpunit --filter <test name> <class name> <file path>` it works:

``` sh
$ phpunit --filter testShow BillingInfoController tests/controllers/BillingInfoControllerTest.php
..                                                                  2 / 2 (100%)

Time: 778 ms, Memory: 39.50MB

OK (2 tests, 4 assertions)
```

When I installed this plugin (like a month ago) it was working fine, but since last week it doesn't, I've updated emacs to `25.1.1` and phpunit to `5.5.4`.

Thanks for the help.

**Comment by nlamirault** [comment]
Could you please put the PHP file you use. Thanks

**Comment by ZzAntares** [comment]
Sure, this is the most basic version of the file, which for me still is not running just one test:

``` php
<?php

use App\Models\BillingInfo;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class BillingInfoController extends TestCase
{
    use WithoutMiddleware;
    use DatabaseMigrations;

    public function testShow()
    {
        factory(BillingInfo::class)->create();

        $this->json('GET', action('BillingInfoController@show', 1))
             ->seeJsonEquals(BillingInfo::find(1)->toArray());
    }
}
```

This is a test in a Laravel project (however I don't think it matters).

Thanks for the help!

**Comment by ZzAntares** [comment]
Duh!, I see my mistake, the class name! needed the `Test` at the end, just seeing it as I post the file 😞 

It's working fine, sorry!

**Comment by nlamirault** [comment]
:) Great.
