### ISSUE TITLE
Release failure

### ISSUE THREAD

**Issue by zonuexe** [nlamirault/phpunit.el#37]
`0.13.0` released in [MELPA stable/phpunit](https://stable.melpa.org/#/phpunit).  But it is still old in [MELPA/phpunit](https://melpa.org/#/phpunit).

It seems to merge direction is wrong.

Correctly it should be displayed as follows:

> merged <var>n</var> commits into `master` from `develop`
#35 is reversed.
## Solution

We can choose the future of development policy.
- A: include `:branch "develop"` to [MELPA recipe](https://github.com/melpa/melpa/blob/master/recipes/phpunit)
- B: abolish `develop` branch

Since MELPA stable now exists, the `develop` branch strategy is not seem to function effectively.

**Comment by nlamirault** [comment]
We can release the "development" branch. The "master" branch could be used for MELPA, and tags for MELPA Stable.
