### ISSUE TITLE
Change phpunit run command

### ISSUE THREAD

**Issue by olymk2** [nlamirault/phpunit.el#38]
often you may want to run your tests inside a container or virtualenv which has the dependencies to run the tests, could we add the ability to change the phpunit command to be something like 

```
docker exec -it container phpunit [extra params]
```

this way we can run the test inside the container or aother environment, and change the options per project.

or is this already available some how ?

**Comment by zonuexe** [comment]
@olymk2 #39 merged and [phpunit.el 0.14.0](https://github.com/nlamirault/phpunit.el/releases/tag/0.14.0) released.

**Comment by olymk2** [comment]
@zonuexe thats great news I will be making use of this when i get a few moments :)
