### ISSUE TITLE
Exact Class Names and Naming Conventions

### ISSUE THREAD

**Issue by muddletoes** [nlamirault/phpunit.el#8]
Currently, if you have two classes with similar names such as follows below, `M-x phpunit-current-class` will, if called in the buffer of the first instance, result in all tests being run for both classes:
+ MyClass
+ MyClassSubclass

Looking at the PHPUnit docs, it is clear that these two classes can only have unit tests with exact class names as follows:
+ MyClassTest
+ MyClassSubclassTest

I think that it would be possible to eliminate most erroneous test-running with a change in the `--filter` pattern passed to phpunit.  There would still be difficulties in situations where identically-named classes existed in different namespaces, such as below; that seems like a much more difficult problem to solve:
+ alpha\MyClassTest
+ beta\MyClassTest

However, the vast majority of false matches could be eliminated.

~~I'm going to be busy for a couple of hours, but I will send a pull request for you to consider later this evening.  (EST)~~

**Comment by muddletoes** [comment]
It is going to take me longer than I thought.  The PCRE part isn't hard, but the improved command needs to work from within both the class file and the unit test file, and I don't think that I can get around testing for that in elisp and maybe adding some conditional expressions.  

Lisps are extremely unfamiliar territory to me.  I've got the basic hang of the debugger/documentation, though, so I'll keep you posted.  I hope to get a chance to spend more time on it sometime later in the week.

**Comment by muddletoes** [comment]
Working version [muddletoes / phpunit.el @ 5bc91e6](https://github.com/muddletoes/phpunit.el/commit/5bc91e62a778c36854026836b28558c38e5903cd) is available to review, although I haven't tested it enough to submit a pull request.  It's also markedly clunky compared to the rest of the code.

**Comment by muddletoes** [comment]
Pull request submitted.

**Comment by nlamirault** [comment]
Thanks for PR.
